### PR TITLE
Project #7 Using Bootstrap

### PR DESCRIPTION
**Pull request by realisticattorney**
I've cloned the newsweek page using bootstrap using two breaking points (from 768px and 992px). The challenge was to accommodate each section in a different order (up & down) and direction (rows & columns), and size/proportion.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

**Please have a look at the suggestions to get more understanding.**

- [ ] Make your PR descriptive. 

- [ ] Please work on the inline comments.

- [ ] Extra white space is present under the **Top Story** section. It is not present on the original page. Please work on it. 

**Clone**

chrome-capture (3)

- [ ] Editor Pick must present in the center. This is how it is present on the original page. 

**clone**

chrome-capture (5)

- [ ] On the original page, there are categories mentioned here. Please compare them. 

**clone**

chrome-capture (6)

**Original**

chrome-capture (7)

- [ ] Your clone missing U.S, World, Business, Tech & Science, Sports, and Culture sections. 

- [ ] Subscribe and Newsletter section doesn't match the original one. 
      - Both sections should have the same height. 
**Original** 

chrome-capture (9)

      - There should less space between text and images
**Clone**

chrome-capture (8)

- [ ] Your footer is not like the original page. Please compare them. 

**clone**

chrome-capture (10)

**Original**

chrome-capture (11)



**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 
Hello @realisticattorney ,
Well done in getting this far with this project.
We are almost there in meeting all the requirements needed for this project to be approved.
There are still some changes that were requested by the previous TSE that you are yet to implement.
- [ ] Please move the style in the index page to a separate CSS file.
- [ ] Avoid the use of `!important` in your CSS.
- [ ] An image in the 'In The Magazine' section' is
Screenshot from 2020-11-19 23-06-24
 not loading on your webpage.
- [ ] The images in the 'Editor's Pick' section has some tag embedded in the image. It is missing in yours, please add them accordingly.
- yours 
Screenshot from 2020-11-19 23-09-16
- original
Screenshot from 2020-11-19 23-10-04
- [ ] Your subscribe and newsletter section doesn't entirely look like the original.
- yours
Screenshot from 2020-11-19 23-13-48
- original
Screenshot from 2020-11-19 23-14-29
- [ ] The footer also needs to be worked on to make it looks exactly as it is in the original.
- yours 
Screenshot from 2020-11-19 23-15-46
- original
Screenshot from 2020-11-19 23-16-28
Please request another review when you finish making the requested changes
slack(@ebeagusamuel)

**Comment by realisticattorney** [comment]
That's not how the project last commit looks. I guess you're looking at the live demo which takes some time to update.
proof2

**Comment by realisticattorney** [comment]
proof3

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 
Hi @realisticattorney 
Your project is almost ready for approval.
Just a tiny change to be made now.
- [ ] Please you need to enable linter check on your project. I forgot to point that out in the last review. You can either use GitHub actions or stickler. You can use this [link](https://github.com/microverseinc/linters-config) to set up GitHub action
- [ ] Please avoid the use of `!important` in your css.
- [ ] The image talked about in the last review is still not loading. I think it is because it is a .webp file. Try downloading a .jpg image and I am positive it will work.
- [x] The tags for the images in the editor's pick are still not added. Please add the tags to those images as it is on the original website.
Just these few changes and your project should be approved.
Please request another review when you are done.
slack(@ebeagusamuel)

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Requeired :recycle: 

## Hi @realisticattorney 
Well done implementing the changes required by the previous TSEs.
However, there are still some changes to be made before this project can be approved.

## [REQUIRED]

- [ ] Fix linter error
- [ ] Your newsweek logo isn't same as the original
- [ ] Your navbar should spread across and not aligned to the left.
- [x] Your subscribe and newsletter section should look exactly like the original in terms of height.
- [x] The **free sign up** button in newsletter section looks different from the original. The whole section itself also has a shade of gray as its border on the original which is missing in yours.

### Make the required changes and submit for another review.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by realisticattorney** [comment]
newsweeklogo

**Comment by realisticattorney** [comment]
I couldnt find any difference between logos

**Comment by realisticattorney** [comment]
done

in my browser looks done

**Comment by kelvin8773** [comment]
# Project Approved 😄 🆗 

Hey, German,

Congratulation! 👍  Nice job on finishing this project, quite a journey, and thanks for keeping it up. 👍 💯 🥇 

## [Optional] 
This project has been done professionally, however, there still room to improve if you want to learn more.

- [ ] Fix the font issue in the header (the weather info). 
Snipaste_2020-11-20_12-51-29

- [ ] Encourage the use of the `<main>` tag for the dominant content of the <body> of a document

- [ ] Clean up unused code or comment to make them look more professional.
Snipaste_2020-11-20_13-08-53

That is it, and hope you enjoy coding and have a nice day!

Kelvin

PS: if you have any issues, feel free to reach me @kelvin in Slack.

**Pull request merged**
